### ISSUE TITLE
Had to add a couple of lines to the code to get the WiFi scan to start

### ISSUE THREAD

**Issue by ChiefPoints** [G6EJD/ESP32-Site-Survey-Tool#1]
Hello,

Just an FYI, I had to alter the code to get the wifi to start scanning. As originally written, I was getting this error in serial console:

`E (######) wifi: esp_wifi_scan_start 967 wifi not start`
 
and I'd get blanks under SSID and a line of 0's under RSSI

Works perfectly after I added the following:
```
    WiFi.disconnect();
    delay(100);

```
Directly under:
`    WiFi.mode(WIFI_STA);                // Put ESP32 into Station Mode`

I thought maybe I may of had an access point already setup on this module from a previous project and maybe that was causing the scan to fail to start, and the disconnect command fixed that, so I put the code back the way it was and reflashed. It went back to the error, so it definitely needed the WiFi.Disconnect();

Thanks for sharing all your projects!

Chief

**Comment by G6EJD** [comment]
Thanks I've changed the code to add this fix.
